### ISSUE TITLE
Upgrade ember-cli-htmlbars

### ISSUE THREAD

**Issue by devinus** [jkusa/ember-cli-clipboard#12]
This will get rid of these warnings in projects that depend on `ember-cli-clipboard`:

```DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/devinus/Projects/rebelmail-dashboard/node_modules/ember-cli/lib/models/addon.js:1009:27)```

**Comment by manuel-reil** [comment]
+1

**Comment by les2** [comment]
👍
