### ISSUE TITLE
Need test helpers for writing integration tests that use this component.

### ISSUE THREAD

**Issue by les2** [jkusa/ember-cli-clipboard#14]
I haven't trouble triggering success / error handlers successfully in tests.

These lines shed some insight on the problems: https://github.com/jkusa/ember-cli-clipboard/blob/fdb2b8cdc42065b525bb11fb4ec77204483d3786/tests/integration/components/copy-button-test.js#L65-L69

This is what I'm using so far:

```
import Ember from 'ember';
import CopyButtonComponent from 'ember-cli-clipboard/components/copy-button';

/**
 * A copy button component that is controllable in integration tests.
 */
let Component = CopyButtonComponent.extend({});

if (Ember.testing) {

  // N.B., testing `{{copy-button` sucks!
  // See https://github.com/jkusa/ember-cli-clipboard/blob/fdb2b8cdc42065b525bb11fb4ec77204483d3786/tests/integration/components/copy-button-test.js#L65-L69
  //
  // So we add some magic to make testing it easy.
  Component.reopenClass({
    clipboardService: Ember.Object.create({
      shouldSucceed: true,
    }),
  });

  Component.reopen({
    didInsertElement() {
      // disable default logic
    },
    willDestroyElement() {
      // disable default logic
    },
    click() {
      if (Component.clipboardService.get('shouldSucceed')) {
        this.sendAction('success');
      } else {
        this.sendAction('error', new Error('Simulated clipboard error'));
      }
    },
  });
}

export default Component;
```

This solution is ugly.

A better design would be:
1. `{{copy-button` would use real `service:clipboard` internally with API like: `attach`, `detach`, ...
2. When testing, we can just inject a fake `service:clipboard` into the app

This might also help improve the unit tests of this repo.

Thoughts?

**Comment by jkusa** [comment]
@les2 thanks for bringing up this issue 😄 

With the mock service injection approach, did you have an idea how you would specify what action to trigger?

I did a quick prototype of two test helpers:

 - `clickCopyBtnSuccess(testContext, optionalSelector)`
 - `clickCopyBtnError(testContext, optionalSelector)`

These two methods look up the component instance given an optional selector and call the corresponding action (`error` or `success`). 

With this approach you wouldn't have to configure the behavior (`error` or `success`) of the component for your test case.

Would this work for your tests?

**Comment by les2** [comment]
typing on phone on metro: if you used service in component it's easy to
override in test with mock service and you can make helper to make even
easier.

to override in test, i would just:

```
this.register('service:clipboard', Ember.Servce.create({
   ...
}))

this.inject.service('clipboard', { as: 'mockService'})
```

then one could stub methods as desired with sinon or whatever.

this is how I'm testing my own components that use services (docs for this
have been added to ember guides).

write better message when on laptop. thanks for looking at this!

**Comment by les2** [comment]
sorry this dropped off my radar. i do intend to respond. :trollface:

**Comment by theroncross** [comment]
@jkusa Could you go into more detail on your prototypes? I'm trying to stub a copy-button in the test file with `this.register('component:child-component', StubButtonComponent)`, but having some trouble calling the parent component actions.

**Comment by jkusa** [comment]
@theroncross check out this commit I have on a branch called `test-support`: https://github.com/jkusa/ember-cli-clipboard/commit/5f4610b310b9c443c4ddbfeeee25dcc33b093646

I have added two methods: `clickCopyBtnError` & `clickCopyBtnSuccess` that can be used to call the actions you have registered with the `copy-button` component.

Let me know how it goes.

**Comment by jkusa** [comment]
Release [v0.5.0](https://github.com/jkusa/ember-cli-clipboard/releases/tag/v0.5.0) added both integration and acceptance test helpers that can trigger the `success` and `error` actions. I felt this was an easy way to validate action handlers without a lot of test setup. 

With this addition, I am going to close this issue. @les2 @theroncross please let me know if you have any feedback.

**Comment by les2** [comment]
thanks. and sorry i wasn't more responsive with this.
