### ISSUE TITLE
Unknown helper createSuper error in build

### ISSUE THREAD

**Issue by meirish** [jkusa/ember-cli-clipboard#177]
**Describe the bug**
Seeing this error in CI after adding `ember-cli-clipboard`

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-cli-clipboard]) in ember-cli-clipboard/components/copy-button.js

/build/ember-cli-clipboard/components/copy-button.js: Unknown helper createSuper
```

Oddly the build works locally, and using this fork https://github.com/jkusa/ember-cli-clipboard/pull/80 builds correctly.

Using `ember-source@3.16.3` and `ember-cli@3.16.0`.

**Expected behavior**
The app can build in CI

**Comment by jkusa** [comment]
@meirish I think I actually ran into something [similar](https://github.com/emberjs/ember.js/pull/18831) on another project. Can you try building with `ember-source` >= `3.16.5`?

**Comment by meirish** [comment]
Aha, thank you - I'll try that!

**Comment by meirish** [comment]
Hmm, that didn't seem to fix it - currently tried the 3.16.7. Will keep poking at it though.

**Comment by meirish** [comment]
Also updating `ember-cli` to 3.16.1 (which updated babel) did the trick. Sorry for the noise and thanks for the pointer to that issue!

**Comment by jkusa** [comment]
@meirish no worries. Glad you got it working 👍
