### ISSUE TITLE
Trim spaces functionality  

### ISSUE THREAD

**Issue by bharatmarewad** [jkusa/ember-cli-clipboard#18]
Once copy text using this add-on some times there are spaces added to copied test.

Text to be copied:- "This is awesome add-on"
Text get copied:- "  This is awesome add-on  "

I am using IE 11.

**Comment by jkusa** [comment]
@bharatmarewad are you using `clipboardText` or `clipboardTarget`?

**Comment by bharatmarewad** [comment]
I am using clipboardTarget. Sorry for delay in response.

**Comment by jkusa** [comment]
@bharatmarewad as you probably know, `clipboardText` can be used if you have access to the string before the user clicks on the copy button. While not ideal, you could listen to updates on an `<input>`, store the trimmed value, and give it to `clipboardText`.

Another option could be to add support for the [clipboard.js advanced options](https://github.com/zenorocha/clipboard.js#advanced-options) in this addon. Perhaps a returning closure action could be executed in a dynamic `text` or `target` hook.
