### ISSUE TITLE
wrappable component?

### ISSUE THREAD

**Issue by et** [jkusa/ember-cli-clipboard#19]
Great addon. Works fantastic and it's a huge improvement over zero clipboard.

I was wondering if you would entertain the idea of something that allows you to wrap any DOM element, not just a button.
I'm aware that you can pass a `tagName` to the `copy-button` component, e.g.

```hbs
{{#copy-button tagName='a' clipboardText='text to be copied'}}
  Click To Copy
{{/copy-button}}
```

but it feels a little clunky especially because it auto sets the [copy-btn](https://github.com/jkusa/ember-cli-clipboard/blob/master/addon/components/copy-button.js#L10) class.

My thoughts were creating something like `copy-trigger` that would be a wrapping `span` around the DOM element, e.g.

```hbs
{{#copy-trigger clipboardText='text to be copied'}}
  <button>My button text</button>
{{/copy-trigger}}
```

```hbs
{{#copy-trigger clipboardText='text to be copied'}}
  <a class='btn'>My button text</a>
{{/copy-trigger}}
```

This makes the component DOM type independent and it allows the consumer to make their own decisions. Thoughts?

**Comment by jkusa** [comment]
@et I am glad you have found it useful :)

To be honest, for a while I have been thinking of updating the contract to be something like what you suggested :

```hbs
{{#clipboard-copy text='text to be copied' }}
  Button Text
{{/clipboard-copy}}
```
With a more generic class name as well:  `.clipboard-copy`

That said, I haven't been motivated to update it just to have consumers make code changes and not add a ton of value.

I'm all for allowing devs to make their own decisions, but I also want it to be convenient for the common case.

I would like to understand your use case. Why isn't `<button>` a good fit. Why do you want to use an `<a>` tag?

**Comment by et** [comment]
Thanks for the feedback @jkusa.
The reason why I would use an `<a>` tag would be something along the lines of like:

`<a>Copy Referral Code</a>`

<img width="171" alt="screen shot 2017-04-18 at 1 28 42 pm" src="https://cloud.githubusercontent.com/assets/58678/25149246/fba4202a-243a-11e7-9fea-4b41c7f322ed.png">

or maybe even just a simple span `<span>Copy Referral Code</span>`.

By defaulting to a `<button>`, I essentially have to resort to excessive styling to not make it look like a button.


> That said, I haven't been motivated to update it just to have consumers make code changes and not add a ton of value.

Couldn't the `copy-button` component be left as is and then the `clipboard-copy` component could simple be added to this library?

Let me know what your thoughts are, I'd be happy to help you out with a PR.

**Comment by jkusa** [comment]
@et i see. I feel `<button>` is the best fit semantically and tend to agree that: 

>"if a button doesn’t have a meaningful href, it’s a \<button\>"
https://twitter.com/chriscoyier/status/411195861918429184

`<span>` could be used with `role=button` for screen readers, but [Mozilla warns against it](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role).

For those reasons I would like to keep the `tagName: 'button'` as default. I am still open to changing the contract and `className` as mentioned before. If this [feature](https://github.com/jkusa/ember-cli-clipboard/issues/18#issuecomment-293762049) goes forward, it could be a motivating factor to update the interface.

> Couldn't the copy-button component be left as is and then the clipboard-copy component could simple be added to this library?

I would rather just have one component to maintain, test, and document. Perhaps the two could exists together if the old one was deprecated and then eventually removed.

**Comment by et** [comment]
> @et I see. I feel <button> is the best fit semantically and tend to agree that:

No disagreement there, but sometimes it's harder to convince the designers of that 😜 

> I would rather just have one component to maintain, test, and document. Perhaps the two could exists together if the old one was deprecated and then eventually removed.

Makes sense. What would you foresee this single component looking like? `copy-trigger` like I suggested above or something different.
Thanks!
