### ISSUE TITLE
`isClipboardSupported` isn't a method anymore

### ISSUE THREAD

**Issue by wagenet** [jkusa/ember-cli-clipboard#225]
`app/helpers/is-clipboard-supported.js` re-exports `isClipboardSupported` which that is not defined in the source. It was removed in 0678c5b4a7d681a116a05803d655652e83437613.

https://github.com/jkusa/ember-cli-clipboard/blob/master/app/helpers/is-clipboard-supported.js#L3

**Comment by jkusa** [comment]
@wagenet nice catch 👍  

Did that end up breaking something for you? Do you have a use-case around invoking`isClipboardSupported` as a JS function (opposed to a template helper)?

**Comment by wagenet** [comment]
@jkusa we could probably refactor now to not need it, but we had a non-Octane component that was using it change the class name.

**Comment by jkusa** [comment]
Resolved via #337
