### ISSUE TITLE
request - add support for `target` / dynamically set target

### ISSUE THREAD

**Issue by ctcpip** [jkusa/ember-cli-clipboard#23]
see 'Advanced Usage' section here: https://clipboardjs.com/

**Comment by ctcpip** [comment]
I had to create my own component that extends this one in order to get this functionality.  It would be nice if it was built in.

**Comment by jkusa** [comment]
@ctcpip I agree this support could be nice. Adding it actually came up in #18.

The trick would be the interface. I am initially thinking the component could take a returning closure action.

Do you mind sharing the case where you needed a dynamic target? Was a `clipboardTarget` computed property not a good fit?

**Comment by ctcpip** [comment]
@jkusa - A computed property would not have worked for me as I need knowledge of the DOM element in question, and `this.$()` would only give you the container.  Anyhow, the trouble is with the lifecycle.  I was able to set the clipboardTarget dynamically but it didn't matter because `didInsertElement()` had already fired within the `copy-button` component.  So the only way to accomplish the goal was to extend the component, and write my own `didInsertElement()` which looks like the following: (I've left out some code, but you get the idea.)

```
  didInsertElement() {
    $this.attr('data-clipboard-target', myTarget;
    this._super();
  }
```
