### ISSUE TITLE
Garbage files in the npm package?

### ISSUE THREAD

**Issue by san650** [jkusa/ember-cli-clipboard#31]
It looks like ember-cli-clipboard v0.8.0 contains a `node_modules.b/` folder with tons of npm packages in it.

It seems this folder was included in the package by mistake.

<img width="532" alt="installed files" src="https://user-images.githubusercontent.com/1234607/32460312-1dbdc8bc-c311-11e7-9bb7-dbf651056326.png">

**Comment by jkusa** [comment]
@san650 good catch! I have released [v0.8.1](https://github.com/jkusa/ember-cli-clipboard/releases/tag/v0.8.1) which does not contain the extra files.  Thanks for reporting the issue.
