### ISSUE TITLE
Bug: 'cannot use elementId on a tag-less component'

### ISSUE THREAD

**Issue by Mifrill** [jkusa/ember-cli-clipboard#356]
```
Uncaught Error: Assertion Failed: You cannot use `elementId` on a tag-less component: <project-name@component:copy-button::ember1892>
```

**To Reproduce**

bump from `"ember-cli-clipboard": "0.13.0",` to `"ember-cli-clipboard": "0.15.0",`

**Additional context**

```
"ember-source": "~3.1.0",
```
Most likely, this is the source of this issue https://github.com/emberjs/ember.js/issues/16177

Usage of:
```
import { tagName } from '@ember-decorators/component';

@tagName('')
```
instead of:
```
tagName = '';
```
solves this issue

**Comment by jkusa** [comment]
Hey @Mifrill 👋 , can you please indicate how to  reproduce this issue? Also, in your code are your trying to access `elementId` directly? This library does not use `elementId` and [sets the id of the button element](https://github.com/jkusa/ember-cli-clipboard/blob/main/addon/components/copy-button.js#L27-L28), so I am a little surprised to see this error.

**Comment by Mifrill** [comment]
@jkusa Thanks for the response. Well about reproduce steps - sure, but I just use component and nothing more:
```
<CopyButton @clipboardText={{this.identityPin}} @class="btn btn-link">
  {{t "admin.manageUsers.copyPin"}}
</CopyButton>
```
for version `0.13.0` all was good, this error raised on bump "ember-cli-clipboard" to "0.15.0"
I did nothing more, just change the version.

It's probably related to ember version, or some polyfill's, not sure, here is list for some packages:
```
"ember-angle-bracket-invocation-polyfill": "3.0.0",
"ember-decorators-polyfill": "^1.1.5",
"ember-source": "~3.1.0",
```
not sure if I can put more specific, as I said: I did nothing special, this error inside CopyButton and was solved when I did apply changes:
```
"ember-cli-clipboard": "Mifrill/ember-cli-clipboard#bugfix/tag-name",
```

**Comment by Mifrill** [comment]
@jkusa I think, it's nice to release it as a patch semantic version, WDYT?
not sure if it's required `ember-decorators` package as one more dependency

**Comment by Mifrill** [comment]
well, it looks like, it's required ember-decorators package as one more dependency:
```
Error: Could not find module `@ember-decorators/component` imported from `ember-cli-clipboard/components/copy-button`
    at missingModule (/tmp/tests-dist-202163-1711-tpaij0.11vze/assets/vendor/loader/loader.js:247:1)
```

**Comment by Mifrill** [comment]
Hey @jkusa here is the repo with bug reproduce:
https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component
As you can see error raised with "normal" component usage:
```
{{#copy-button clipboardText="HELLO WORLD" class="btn btn-link"}}
  TEXT
{{/copy-button}}
```
we've using https://github.com/ember-polyfills/ember-angle-bracket-invocation-polyfill, but issue the same:
```
<CopyButton @clipboardText="HELLO WORLD" @class="btn btn-link">
  TEXT
</CopyButton>
```
https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component/blob/6543f6582df9ef5ed1415ff1967558328667a022/app/templates/application.hbs#L4-L6

Error:
```
Uncaught Error: Assertion Failed: You cannot use `elementId` on a tag-less component: <demo-ember-cli-clipboard-bug-cannot-use-element-id-on-a-tag-less-component@component:copy-button::ember260>
```
https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component/runs/3265760647?check_suite_focus=true

Bugfix with decorator usage for `tagName`:
https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component/pull/1

**Comment by Mifrill** [comment]
@jkusa as you can see, it's working fine on version "0.13.0":
https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component/pull/2

**Comment by Mifrill** [comment]
Hey, @jkusa any thoughts about https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component?

**Comment by Mifrill** [comment]
https://github.com/emberjs/ember.js/issues/16177#issuecomment-476921328

**Comment by Mifrill** [comment]
Base on experiments starts from Ember 3.6 this bug was solved:
![Selection_849](https://user-images.githubusercontent.com/23525618/135986888-8b42efc5-dd77-4bda-86d1-e9251443af4e.jpg)
Source: https://github.com/Mifrill/demo-ember-cli-clipboard-bug-cannot-use-elementId-on-a-tag-less-component/pull/5

Hence, I think, it's simpler to use version [0.13](https://github.com/jkusa/ember-cli-clipboard/releases/tag/v0.13.0) for Ember 3.1 - 3.5 and version [0.14](https://github.com/jkusa/ember-cli-clipboard/releases/tag/v0.14.0) or upper for the following upgraded versions to avoid `ember-decorators` dependency.
