### ISSUE TITLE
prop-types dependency resolution

### ISSUE THREAD

**Issue by meirish** [jkusa/ember-cli-clipboard#388]
**Describe the bug**
I was looking into an embroider migration, but kept running into an addon in our monorepo not being able to find `copy-button.js`. So when I tried building that addon independently, I get the following error:

```
ember-cli-clipboard needs prop-types satisfying ^15.8.1, but we have version 15.7.2 because of ember-arg-types
```

It looks like `ember-arg-types` needs to have the `prop-types` dependency to `^15.8.1` - it's currently at `^15.7.2`.

**Comment by jkusa** [comment]
fixed via jkusa/ember-arg-types#99
