### ISSUE TITLE
is there a way to not highlight the target text?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jkusa/ember-cli-clipboard#39]
I'm using copy to copy code from a pre/code element, and when I click copy it get's highligthed. I was wondering if there was a way to disable that?

**Comment by jkusa** [comment]
@NullVoxPopuli I have seen the highlight behavior with a `<input>` element.

While there is no direct way, Clipboard.JS provides `clearSelection()` to move focus off the target:
https://github.com/zenorocha/clipboard.js/issues/512#issuecomment-362154957


Here is how you would do this with `ember-cli-clipboard`:
```hbs
{{#copy-button
  clipboardTarget=".target"
  success=(action 'onSuccess')
 }}
  Click To Copy                                                                                                  
{{/copy-button}}
```

```js
  actions: {
    onSuccess(e) {
      e.clearSelection();
    }                                                                                                                                                
  }
```

Let me know if you have further questions.

**Comment by NullVoxPopuli** [comment]
perfect! thanks!
