### ISSUE TITLE
Package no longer works in Firefox

### ISSUE THREAD

**Issue by chrissvo** [jkusa/ember-cli-clipboard#4]
Ends in to error callback after copy action.

Maybe needs a newer version of clipboard.js: https://github.com/zenorocha/clipboard.js/issues/104

**Comment by chrissvo** [comment]
Issue only occurs in FF41. Just tested with FF42 and that works fine, so closing!

**Comment by jkusa** [comment]
@chrissvo thanks for the heads up. I just published a release that brings in clipboard.js `~1.5.5`
