### ISSUE TITLE
Declare `@ember/string` as `peerDependency`

### ISSUE THREAD

**Issue by mkszepp** [jkusa/ember-cli-clipboard#409]
The addon is using `@ember/string`, but there is not declared as peerDependency.

https://github.com/jkusa/ember-cli-clipboard/blob/63c624ff0b570eea298e0d03c78ac338824e61af/addon/modifiers/clipboard.js#L1-L6

**Comment by elwayman02** [comment]
I'm seeing Webpack throw test errors due to this issue:

> message: ember-cli-clipboard tried to import "@ember/string" in "ember-cli-clipboard/modifiers/clipboard.js" from addon code, but "@ember/string" is a devDependency. You may need to move it into dependencies.

This occurs when bumping @ember/string from v3 to v4, likely because it's now a real module which requires ember-auto-import/embroider to consume. See also: https://github.com/emberjs/ember-string/pull/425

**Comment by jkusa** [comment]
Update for this now available in [v1.2.0](https://github.com/jkusa/ember-cli-clipboard/releases/tag/v1.2.0)
