### ISSUE TITLE
@ember/test-helpers in devDependencies

### ISSUE THREAD

**Issue by bmaehr** [jkusa/ember-cli-clipboard#416]
**Describe the bug**
```
Build Error (WebpackBundler)

ember-cli-clipboard tried to import "@ember/test-helpers" in "ember-cli-clipboard/test-support/index.js" from addon code, but "@ember/test-helpers" is a devDependency. You may need to move it into dependencies.
```

Additional dependencies:
ember-auto-import: "2.8.1"
webpack: "5.95.0"

Even moving it there didn't solve the problem

**Comment by bertdeblock** [comment]
Running into the same issue.
`ember-cli-clipboard` needs to define a peer dependency on `@ember/test-helpers`.
