### ISSUE TITLE
sendAction deprecation

### ISSUE THREAD

**Issue by samselikoff** [jkusa/ember-cli-clipboard#53]
sendAction is throwing a deprecation warning, any reason we're still using it?

If not I can send a PR with a refactor

**Comment by jkusa** [comment]
Hey @samselikoff, what version of the addon are you using? Starting with `v0.11.0` `sendAction` will not be called unless you pass a string as an action handler. This legacy support will be removed entirely in the near future.

**Comment by samselikoff** [comment]
I'm on `0.11.1` and not passing any action args in, just using it like this:

```hbs
{{#copy-button
  clipboardText=snippetText
  title='copy to clipboard'
  class='
    docs-absolute docs-pin-t docs-pin-r docs-bg-transparent hover:docs-bg-transparent
    docs-border-none docs-opacity-50 hover:docs-opacity-100 docs-p-3 docs-text-white
  '
}}
  Copy
{{/copy-button}}
```

**Comment by jkusa** [comment]
Hmm, I just created a new app with `ember-cli-clipboard-0.11.1` and didn't see any warnings.

`sendAction` is only used when a `success` or `error` action is fired with a string action handler:

https://github.com/jkusa/ember-cli-clipboard/search?q=sendAction&unscoped_q=sendAction

Can you post the warning message you are seeing?

**Comment by samselikoff** [comment]
Yep:

> deprecate.js:102 DEPRECATION: You called <dummy@component:copy-button::ember381>.sendAction("success") but Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.

Sorry for taking your time, I should try to reproduce on my end first to see if something else is going on. Will report back.

**Comment by samselikoff** [comment]
Turns out I had two versions of ember-cli-clipboard in my app :)

ember-cli-tailwind was depending on an older version, ember-cli-addon docs the more recent one.

Funnily enough, I literally just wrote about this topic yesterday: http://www.ember-cli-mirage.com/blog/how-to-reliably-override-npm-dependencies-1497

What a mess!

Sorry about the distraction :) Thanks for maintaining such a useful lib that I use it in all of mine!

**Comment by jkusa** [comment]
@samselikoff No worries, glad you found the root cause!
