### ISSUE TITLE
Is there a way to hide the input? 

### ISSUE THREAD

**Issue by lenoraporter** [jkusa/ember-cli-clipboard#55]
When I set type="hidden" or display:none, the copy button fails to work. It works fine while the input is visible.

Disclaimer: I tried to set the text directly but the text is generated so I can't do that. I also tried some of the clipboard.js solutions but it didn't work.

**Comment by jkusa** [comment]
Hi @lenoraporter, yes it looks like clipboard.js will not work with ` type="hidden"` or `display:none`.

> Disclaimer: I tried to set the text directly but the text is generated so I can't do that. I also tried some of the clipboard.js solutions but it didn't work.

Did you try to use a computed property as the `clipboardText`?

Example: https://ember-twiddle.com/f1622f9a1c39423caadca74e2a5a211c?openFiles=templates.application.hbs%2C

**Comment by lenoraporter** [comment]
Perfect! This works! Thanks a ton!
