### ISSUE TITLE
Option to stop bubbling the action in the DOM.

### ISSUE THREAD

**Issue by girdhariag** [jkusa/ember-cli-clipboard#71]
**Is your feature request related to a problem? Please describe.**
I was trying to implement this inside an actionable element in the dom. Though the copy was successful, the click event was bubbled to the outer element too.

**Describe the solution you'd like**
By default can we have bubbling as false or at least can we have an option to send from the consuming component.

**Comment by jkusa** [comment]
@girdhariag can you post a code sample (or ember twiddle) of the problem you are facing.

**Comment by girdhariag** [comment]
```hbs
<button {{action "btnAction"}}>
    {{#copy-button clipboardText="Text to be copied" success=(action "successHandler") error=(action "errorHandler")}}
        Copy this text
    {{/copy-button}}
</button>
```

What we want is when we click on the `Copy this text`, the action `btnAction` shouldn't be triggered.

**Comment by girdhariag** [comment]
@jkusa

**Comment by bmaehr** [comment]
Don't know why but delegateClickEvent= false fixes some of the handling for me. I can create a dummy action around stopping propagation.

**Comment by jkusa** [comment]
`delegateClickEvent=false` adds the event listener at the button element, while `delegateClickEvent=false` adds it to `document.body`.

https://github.com/jkusa/ember-cli-clipboard/blob/7e3f448bd1861f9a01b22622e022e646a3fd4449/addon/modifiers/clipboard.js#L14-L15

As @bmaehr mentioned, if you scope it to the element, you are able to stop the event propagation.

**Comment by jkusa** [comment]
@girdhariag is this still a problem you are facing? In your example you are nesting two button elements, which is not valid html for a button btw 😉
> there must be no [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) descendant

https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element

Not sure what your use case is/was, but in the latest version of this library you can now use element modifiers to embed the clipboard behavior into a vanilla element:

```hbs
<button
  class='button is-outline'
  type='button'
  {{clipboard text='text to be copied' onSuccess=this.onSuccess}}
>
  Click To Copy
</button>
```
